In [1]:
import numpy as np
import pandas as pd

In [9]:
df = pd.read_csv("train.csv")
df[30:45]

id  MO HLADR+ MFI (cells/ul)  Neu CD64+MFI (cells/ul)  CD3+T (cells/ul)  \
30  30                    1188.0                     82.0           1108.99   
31  31                    1035.0                     87.0            281.73   
32  32                    1588.0                     92.0           1442.63   
33  33                    1117.0                    336.0            409.14   
34  34                     821.0                    134.0           1134.74   
35  35                     693.0                    245.0            266.48   
36  36                    1436.0                     76.0            813.73   
37  37                     620.0                    472.0            250.43   
38  38                    1010.0                   1384.0            570.13   
39  39                       NaN                      NaN           1336.54   
40  40                    1024.0                    180.0            858.48   
41  41                     222.0                     82.0           1061.47   
42  42                     602.0                     98.0            770.62   
43  43                    1679.0                     79.0            483.21   
44  44                    1365.0                     67.0            841.88   

    CD8+T (cells/ul)  CD4+T (cells/ul)  NK (cells/ul)  CD19+ (cells/ul)  \
30            623.49            483.60         217.11            213.32   
31            124.41            159.52          69.13             41.42   
32            606.07            840.82         325.80            485.86   
33            206.74            209.22          37.87             27.32   
34            741.00            401.00         459.72             23.87   
35            103.61            164.11         147.95             87.03   
36            541.23            276.28         258.81             82.18   
37            150.39             68.66          64.08            125.11   
38            312.90            233.84          80.17             31.18   
39            739.71            550.30          68.46            192.07   
40            673.32            185.61         213.96             50.06   
41            423.27            638.74         246.18            192.45   
42            499.81            276.71         214.92             76.34   
43            162.00            309.00         227.05            101.09   
44            576.19            269.21         174.35             62.80   

    CD45+ (cells/ul)  Age  Sex 0M1F  Mono CD64+MFI (cells/ul)  label  
30           1547.02   49         1                    1947.0      0  
31            394.64   41         0                    1651.0      0  
32           2282.03   35         0                    1365.0      0  
33            475.57   44         1                    3190.0      1  
34           1619.77   41         1                    1893.0      0  
35            504.15   49         0                    2175.0      1  
36           1179.27   42         0                    1794.0      0  
37            439.84   37         1                    1527.0      1  
38            702.08   56         1                    5501.0      1  
39           1615.68   21         0                       NaN      0  
40           1129.59   47         0                    1953.0      0  
41           1519.28   33         0                    1686.0      0  
42           1071.42   49         1                    1566.0      0  
43            817.24   39         0                    4480.0      0  
44           1082.11   29         1                    1830.0      0

In [10]:
df2 = df.dropna()

In [11]:
df2.shape

(86, 13)

In [12]:
df.shape

(87, 13)

In [14]:
X=df2[['MO HLADR+ MFI (cells/ul)', 'Neu CD64+MFI (cells/ul)',
       'CD3+T (cells/ul)', 'CD8+T (cells/ul)', 'CD4+T (cells/ul)',
       'NK (cells/ul)', 'CD19+ (cells/ul)', 'CD45+ (cells/ul)','Mono CD64+MFI (cells/ul)']]
Y = df2['label'] 

In [13]:
df2.columns

Index(['id', 'MO HLADR+ MFI (cells/ul)', 'Neu CD64+MFI (cells/ul)',
       'CD3+T (cells/ul)', 'CD8+T (cells/ul)', 'CD4+T (cells/ul)',
       'NK (cells/ul)', 'CD19+ (cells/ul)', 'CD45+ (cells/ul)', 'Age',
       'Sex 0M1F', 'Mono CD64+MFI (cells/ul)', 'label'],
      dtype='object')

In [15]:
from sklearn.model_selection import train_test_split

In [17]:
y = Y

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [19]:
from sklearn.ensemble import RandomForestClassifier
clf=RandomForestClassifier(n_estimators=100)

In [33]:
clf2 = RandomForestClassifier(n_estimators=50)

In [20]:
clf.fit(X_train,y_train)

RandomForestClassifier()

In [34]:
clf2.fit(X_train,y_train)

RandomForestClassifier(n_estimators=50)

In [35]:
y_pred=clf2.predict(X_test)

In [36]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.8888888888888888


In [37]:
y_test

67    1
84    1
26    1
85    1
16    0
72    0
58    0
5     1
15    0
69    0
63    0
50    0
8     0
41    0
37    1
32    0
76    1
11    0
Name: label, dtype: int64

In [38]:
y_pred

array([1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0])

In [39]:
X2=df2[['MO HLADR+ MFI (cells/ul)', 'Neu CD64+MFI (cells/ul)',
       'CD3+T (cells/ul)', 'CD8+T (cells/ul)', 'CD4+T (cells/ul)',
       'NK (cells/ul)', 'CD19+ (cells/ul)', 'CD45+ (cells/ul)','Mono CD64+MFI (cells/ul)','Age',
       'Sex 0M1F']]

In [40]:
X2_train, X2_test, y2_train, y2_test = train_test_split(X2, y, test_size=0.2)

In [46]:
clf3 = RandomForestClassifier(n_estimators=100)

In [47]:
clf3.fit(X2_train,y2_train)

RandomForestClassifier()

In [48]:
y2_pred=clf3.predict(X2_test)

In [50]:
print("Accuracy:",metrics.accuracy_score(y2_test, y2_pred))

Accuracy: 0.8333333333333334


In [53]:
y3_predict = clf2.predict(X2_test.iloc[:,:-2])

In [54]:
print("Accuracy:",metrics.accuracy_score(y2_test, y3_predict))

Accuracy: 1.0


In [55]:
y2_test

51    0
43    0
80    0
37    1
46    0
31    0
57    1
4     0
16    0
49    1
35    1
34    0
6     0
36    0
48    0
19    1
15    0
17    1
Name: label, dtype: int64

In [56]:
y3_predict

array([0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1])

In [57]:
y2_pred

array([0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0])

In [60]:
import xgboost as xgb
from sklearn.metrics import mean_squared_error

In [66]:
xg_reg = xgb.XGBRegressor(objective ='reg:squarederror', n_estimators = 50)

In [67]:
xg_reg.fit(X_train,y_train)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
             gamma=0, gpu_id=-1, importance_type=None,
             interaction_constraints='', learning_rate=0.300000012,
             max_delta_step=0, max_depth=6, min_child_weight=1, missing=nan,
             monotone_constraints='()', n_estimators=50, n_jobs=8,
             num_parallel_tree=1, predictor='auto', random_state=0, reg_alpha=0,
             reg_lambda=1, scale_pos_weight=1, subsample=1, tree_method='exact',
             validate_parameters=1, verbosity=None)

In [68]:
preds = xg_reg.predict(X_test)

array([ True,  True, False,  True, False, False, False, False, False,
       False, False, False, False, False,  True, False,  True, False])

In [70]:
y_pred

array([1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0])

In [73]:
1*(preds>0.5)

array([1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0])

In [74]:
print("Accuracy:",metrics.accuracy_score(1*(preds>0.5), y_pred))

Accuracy: 1.0


In [78]:
print("Accuracy:",metrics.accuracy_score(1*(xg_reg.predict(X2_test.iloc[:,:-2])>0.5),y2_test))

Accuracy: 1.0


In [77]:
(xg_reg.predict(X2_test.iloc[:,:-2])>0.5)

array([ 6.24834327e-04, -6.77841817e-05, -3.16255988e-04,  1.00044239e+00,
       -1.74376240e-04,  1.45053677e-03,  1.00006187e+00, -2.93048797e-04,
       -1.54525542e-03,  9.99666095e-01,  9.99658048e-01,  4.09163331e-04,
        2.52099562e-04,  2.52099562e-04,  3.97071672e-05,  1.00054073e+00,
       -1.20046055e-02,  9.98727024e-01], dtype=float32)