In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("train.csv")

In [3]:
df2 = df.dropna()

In [4]:
X=df2[['MO HLADR+ MFI (cells/ul)', 'Neu CD64+MFI (cells/ul)',
       'CD3+T (cells/ul)', 'CD8+T (cells/ul)', 'CD4+T (cells/ul)',
       'NK (cells/ul)', 'CD19+ (cells/ul)', 'CD45+ (cells/ul)','Mono CD64+MFI (cells/ul)']]
Y = df2['label'] 

In [5]:
from sklearn.model_selection import KFold

In [6]:
import xgboost as xgb
from sklearn.metrics import mean_squared_error

In [9]:
from sklearn import metrics

In [49]:
xg_reg = xgb.XGBRegressor(objective ='reg:squarederror', n_estimators = 50)

In [41]:
from sklearn.model_selection import RandomizedSearchCV

In [42]:
from sklearn.model_selection import train_test_split

In [76]:
np.random.seed(10)
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.1)

In [50]:
xg_reg.fit(X_train,y_train)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
             gamma=0, gpu_id=-1, importance_type=None,
             interaction_constraints='', learning_rate=0.300000012,
             max_delta_step=0, max_depth=6, min_child_weight=1, missing=nan,
             monotone_constraints='()', n_estimators=50, n_jobs=8,
             num_parallel_tree=1, predictor='auto', random_state=0, reg_alpha=0,
             reg_lambda=1, scale_pos_weight=1, subsample=1, tree_method='exact',
             validate_parameters=1, verbosity=None)

In [51]:
xg_reg.predict(X_test)

array([ 9.9887800e-01,  1.4441020e-02,  1.7620860e-02,  1.6775353e-01,
        1.0599345e-03,  3.6810359e-01,  9.9928528e-01,  6.9519654e-03,
       -1.0630892e-02, -2.5228050e-03,  2.3441793e-02,  4.1257164e-01,
        1.0005049e+00,  5.3713012e-01,  1.6930489e-02, -3.4233194e-03,
       -1.3817761e-04,  1.0008680e+00], dtype=float32)

In [52]:
y_test

14    1
3     0
34    0
21    1
46    0
35    1
57    1
61    0
70    0
73    0
79    1
59    0
38    1
48    0
69    0
43    0
6     0
19    1
Name: label, dtype: int64

In [53]:
preds = xg_reg.predict(X_test)

In [54]:
print("Accuracy:",metrics.accuracy_score(1*(preds>0.5),y_test))

Accuracy: 0.7777777777777778


In [88]:
xg_cls = xgb.XGBClassifier(objective ='binary:logistic', n_estimators = 50)

In [78]:
xg_cls.fit(X_train,y_train)

[18:15:07] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


/Users/lijiangmeng/opt/anaconda3/lib/python3.7/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
              gamma=0, gpu_id=-1, importance_type=None,
              interaction_constraints='', learning_rate=0.300000012,
              max_delta_step=0, max_depth=6, min_child_weight=1, missing=nan,
              monotone_constraints='()', n_estimators=50, n_jobs=8,
              num_parallel_tree=1, predictor='auto', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [79]:
xg_cls.predict(X_test)

array([1, 0, 0, 1, 0, 0, 1, 0, 0])

In [80]:
print("Accuracy:",metrics.accuracy_score(xg_cls.predict(X_test),y_test))

Accuracy: 0.8888888888888888


In [112]:
from sklearn.ensemble import RandomForestClassifier
clf=RandomForestClassifier(n_estimators=50)

In [82]:
clf.fit(X_train,y_train)

RandomForestClassifier(n_estimators=50)

In [83]:
print("Accuracy:",metrics.accuracy_score(clf.predict(X_test), y_test))

Accuracy: 0.8888888888888888


In [74]:
clf.predict(X_test)

array([1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1])

In [75]:
print("Accuracy:",metrics.accuracy_score(clf.predict(X_test), xg_cls.predict(X_test)))

Accuracy: 0.8888888888888888


In [84]:
clf.predict(X_test)

array([1, 0, 0, 1, 0, 0, 1, 0, 0])

In [85]:
y_test

14    1
3     0
34    0
21    1
46    0
35    1
57    1
61    0
70    0
Name: label, dtype: int64

In [90]:
xg_cls.fit(X,Y)

[18:22:17] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


/Users/lijiangmeng/opt/anaconda3/lib/python3.7/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
              gamma=0, gpu_id=-1, importance_type=None,
              interaction_constraints='', learning_rate=0.300000012,
              max_delta_step=0, max_depth=6, min_child_weight=1, missing=nan,
              monotone_constraints='()', n_estimators=50, n_jobs=8,
              num_parallel_tree=1, predictor='auto', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [113]:
clf.fit(X,Y)

RandomForestClassifier(n_estimators=50)

In [91]:
df3 = pd.read_csv("test.csv")

In [101]:
df3[0:58]

id  MO HLADR+ MFI (cells/ul)  Neu CD64+MFI (cells/ul)  CD3+T (cells/ul)  \
40  40                    1784.0                    474.0            337.75   
41  41                     676.0                     64.0            622.25   
42  42                     629.0                     76.0            427.06   
43  43                     721.0                    117.0            983.00   
44  44                    1733.0                    134.0           1443.62   
45  45                    1546.0                    184.0            832.08   
46  46                     838.0                    226.0           1025.32   
47  47                     740.0                    187.0            530.77   
48  48                     494.0                     61.0           1568.54   
49  49                    1700.0                     71.0           1106.54   
50  50                    1175.0                     60.0            847.11   
51  51                    1956.0                    152.0           1786.48   
52  52                    1122.0                     66.0           1955.03   
53  53                    2492.0                     60.0           2278.56   
54  54                     708.0                    248.0           1304.86   
55  55                     560.0                     74.0            727.01   
56  56                    1948.0                    264.0           1836.00   
57  57                    1010.0                     90.0           1061.65   

    CD8+T (cells/ul)  CD4+T (cells/ul)  NK (cells/ul)  CD19+ (cells/ul)  \
40            133.11            204.64          25.50             16.00   
41            345.00            221.00          50.60             56.04   
42            240.16            138.57          83.83              2.96   
43            449.00            539.00         141.00             76.00   
44            770.62            613.22          85.40            227.47   
45            621.01            210.58         141.36             63.86   
46            728.71            296.61         187.36            135.49   
47            154.69            377.34          40.07             45.14   
48            937.00            601.00         246.48            165.92   
49            503.71            547.54         363.45            176.67   
50            362.52            486.42         512.66            116.57   
51            783.82            952.42         194.75            198.19   
52           1080.16            879.77         111.60            100.20   
53            937.47           1225.68         252.10            304.97   
54            433.61            789.19         257.43            122.28   
55            227.25            502.48         159.80            106.38   
56            838.96            819.69         184.56            105.53   
57            379.12            683.06          99.71             76.25   

    CD45+ (cells/ul)  Age  Sex 0M1F  Mono CD64+MFI (cells/ul)  
40            379.25   42         0                    6788.0  
41            731.13   29         0                    1660.0  
42            525.20   42         0                    1391.0  
43           1200.00   37         0                    2771.0  
44           1760.90   42         1                    1501.0  
45           1043.63   51         0                    2281.0  
46           1358.55   38         1                    1662.0  
47            618.76   31         0                    2617.0  
48           1983.61   38         0                    1923.0  
49           1650.03   48         0                    1617.0  
50           1486.10   47         0                    2013.0  
51           2188.36   40         1                    2251.0  
52           2201.04   30         0                    1468.0  
53           2864.00   21         1                     924.0  
54           1691.81   37         1                    1669.0  
55           1011.29   54         0                 

In [96]:
V = df3[['MO HLADR+ MFI (cells/ul)', 'Neu CD64+MFI (cells/ul)',
       'CD3+T (cells/ul)', 'CD8+T (cells/ul)', 'CD4+T (cells/ul)',
       'NK (cells/ul)', 'CD19+ (cells/ul)', 'CD45+ (cells/ul)','Mono CD64+MFI (cells/ul)']]

In [100]:
len(V)

59

In [97]:
labels = xg_cls.predict(V)

In [114]:
labels2 = clf.predict(V)

In [115]:
len(labels2)

59

In [116]:
import csv

In [117]:
file = open('sample_submission.csv', 'w+')

In [118]:
lst1 = range(59)
lst2 = labels2
dataframew = pd.DataFrame({'id':lst1,'label':labels})

In [119]:
dataframew.to_csv("sample_submission.csv",index=False)

In [120]:
dataframew[['id','label']].head()

id  label
0   0      0
1   1      0
2   2      0
3   3      0
4   4      0

In [110]:
labels

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1])

In [111]:
V[0:10]

MO HLADR+ MFI (cells/ul)  Neu CD64+MFI (cells/ul)  CD3+T (cells/ul)  \
0                    2843.0                    156.0           1358.52   
1                     437.0                    137.0            509.43   
2                     826.0                     82.0           1232.22   
3                     861.0                     50.0           1512.86   
4                    1160.0                    157.0            890.42   
5                     867.0                     85.0           1662.11   
6                    1330.0                    114.0           1307.95   
7                     494.0                     48.0           1522.39   
8                    2119.0                     73.0           1219.66   
9                    2052.0                     39.0           1223.65   

   CD8+T (cells/ul)  CD4+T (cells/ul)  NK (cells/ul)  CD19+ (cells/ul)  \
0            730.78            637.85         127.06             94.82   
1            268.05            243.07         390.86             98.24   
2            493.42            744.08         516.28            320.15   
3            925.51            590.07         380.25             25.80   
4            403.91            489.53         266.92             87.63   
5            865.50            804.14         220.68             92.58   
6            710.86            607.96         271.01            214.49   
7            618.19            911.49         338.85            104.45   
8            732.14            468.48          71.54             83.08   
9            642.55            565.39         323.67            153.64   

   CD45+ (cells/ul)  Mono CD64+MFI (cells/ul)  
0           1588.62                    3256.0  
1           1002.76                     491.0  
2           2200.58                    1381.0  
3           1929.10                    1377.0  
4           1251.52                    1844.0  
5           2063.11                     986.0  
6           1855.05                    2077.0  
7           2013.05                    1409.0  
8           1378.32                    2403.0  
9           1711.88                    1701.0

In [121]:
labels2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [122]:
xg_reg = xgb.XGBRegressor(objective ='reg:squarederror', n_estimators = 50)

In [123]:
xg_reg.fit(X,Y)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
             gamma=0, gpu_id=-1, importance_type=None,
             interaction_constraints='', learning_rate=0.300000012,
             max_delta_step=0, max_depth=6, min_child_weight=1, missing=nan,
             monotone_constraints='()', n_estimators=50, n_jobs=8,
             num_parallel_tree=1, predictor='auto', random_state=0, reg_alpha=0,
             reg_lambda=1, scale_pos_weight=1, subsample=1, tree_method='exact',
             validate_parameters=1, verbosity=None)

In [124]:
preds = xg_reg.predict(V)

In [125]:
preds1 = xg_reg.predict(X)

In [126]:
print("Accuracy:",metrics.accuracy_score(1*(preds1>0.5), Y))

Accuracy: 1.0


In [128]:
labels3 = 1*(preds>0.5)

In [129]:
file = open('sample_submission.csv', 'w+')

In [130]:
lst1 = range(59)

dataframew = pd.DataFrame({'id':lst1,'label':labels2})
dataframew.to_csv("sample_submission.csv",index=False)